name: Userge Hooman

on:
  push:
    branches: [ hooman ]
    paths-ignore: 'README.md'
  workflow_dispatch:
    
env:
  GitHubMail: "BleedingDevX97@Protonmail.com"
  GitHubName: "LinuxSupremacyX" 
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: Set Git Configs & Secrets
         run: |
           git config --global user.email ${GitHubMail}
           git config --global user.name ${GitHubName}
           git config --global credential.helper store
           echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
       - name: cloning repo
         continue-on-error: false
         run: |
           git clone -b hooman https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.CREDS }} userge
       - name: Running Userge
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd userge
           docker-compose up -d
           docker-compose logs -f
       - name: Loop workflow
         continue-on-error: true
         run: |
           git clone -b hooman https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
           cd loop || exit 1
           echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
           git add looper.txt
           git commit -m "Workflow : Loop at $(date -u +%D-%T%P)"
           git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
